/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BoxPackages: typeof import('./src/components/BoxPackages.vue')['default']
    CodeListingPackage: typeof import('./src/components/CodeListingPackage.vue')['default']
    CommentPackage: typeof import('./src/components/CommentPackage.vue')['default']
    DocumentClassSelector: typeof import('./src/components/DocumentClassSelector.vue')['default']
    DocumentContent: typeof import('./src/components/DocumentContent.vue')['default']
    DocumentLayoutPackage: typeof import('./src/components/DocumentLayoutPackage.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    EnglishFontSettings: typeof import('./src/components/EnglishFontSettings.vue')['default']
    FancyhdrPackage: typeof import('./src/components/FancyhdrPackage.vue')['default']
    FigureColorPackage: typeof import('./src/components/FigureColorPackage.vue')['default']
    FontSettings: typeof import('./src/components/FontSettings.vue')['default']
    GeometryPackage: typeof import('./src/components/GeometryPackage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HyperlinkIndexPackage: typeof import('./src/components/HyperlinkIndexPackage.vue')['default']
    LettrinePackage: typeof import('./src/components/LettrinePackage.vue')['default']
    ListSymbolPackage: typeof import('./src/components/ListSymbolPackage.vue')['default']
    MoreWritesPackage: typeof import('./src/components/MoreWritesPackage.vue')['default']
    PackageOptions: typeof import('./src/components/PackageOptions.vue')['default']
    ParallelTextPackage: typeof import('./src/components/ParallelTextPackage.vue')['default']
    TableOfContentsPackage: typeof import('./src/components/TableOfContentsPackage.vue')['default']
    TablePackage: typeof import('./src/components/TablePackage.vue')['default']
    TitleFormatPackage: typeof import('./src/components/TitleFormatPackage.vue')['default']
  }
}
